### ISSUE TITLE
Mention author of diagrams and code

### ISSUE THREAD

**Issue by rauschma** [vasanthk/Simple-promise-library#1]
Please mention that both the diagrams in the readme and the code were created by me:
- Diagrams: http://www.2ality.com/2014/10/es6-promises-api.html
- Code: https://github.com/rauschma/demo_promise

**Comment by vasanthk** [comment]
@rauschma Thank you for the awesome article.
Not sure why this repo I created 7 months ago for learning purposes is getting stars now.
All credits to you, have added it to README.

**Comment by rauschma** [comment]
Ah, got it! Thanks for giving credit!
